In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\sreej\OneDrive\Desktop\Power BI PROJECT\RAW_Global_Nike.csv")

print(df.head())

  snapshot_date country_code     product_name model_number currency  \
0    2026-03-19           US  "Grateful Duck"  NIKGD001K01      USD
1    2026-03-19           US  "Grateful Duck"  NIKGD001K01      USD
2    2026-03-19           US  "Grateful Duck"  NIKGD001K01      USD
3    2026-03-19           US  "Grateful Duck"  NIKGD001K01      USD
4    2026-03-19           US  "Grateful Duck"  NIKGD001K01      USD

   price_local  sale_price_local gender_segment size_label category  ...  \
0        110.0               NaN            MEN          L  APPAREL  ...
1        110.0               NaN            MEN          M  APPAREL  ...
2        110.0               NaN            MEN          S  APPAREL  ...
3        110.0               NaN            MEN         XL  APPAREL  ...
4        110.0               NaN            MEN        XXL  APPAREL  ...

                                       canonical_url  \
0  https://www.nike.com/t/grateful-duck-mens-tie-...
1  https://www.nike.com/t/grateful-duck-mens-tie-...
2  https://www.nike.com/t/grateful-duck-mens-tie-...
3  https://www.nike.com/t/grateful-duck-mens-tie-...
4  https://www.nike.com/t/grateful-duck-mens-tie-...

                                           image_url gtin  \
0  https://secure-images.nike.com/is/image/DotCom...  NaN
1  https://secure-images.nike.com/is/image/DotCom...  NaN
2  https://secure-images.nike.com/is/image/DotCom...  NaN
3  https://secure-images.nike.com/is/image/DotCom...  NaN
4  https://secure-images.nike.com/is/image/DotCom...  NaN

  stock_keeping_unit_id                        catalog_sku_id nike_size  \
0          1.006751e+09  39559a5b-10fa-3043-b76d-3768a55e1497         L
1          1.006751e+09  c86c12ba-1f5a-35e9-b7b1-4b99c951697a         M
2          1.006751e+09  2a8280da-2422-367d-8b62-815fd818558b         S
3          1.006751e+09  f57b1501-4949-367c-9ef2-e0a97950bed1        XL
4          1.006751e+09  33558d9d-c59c-3040-abb7-0504ea8fc36b       2XL

   localized_size                    size_conversion_id  sport_tags  \
0               L  634c88b1-1341-378c-91c2-694b4d4af924    Football
1               M  cb181d5c-38b4-3423-a1a4-aa7d8c6f0bc7    Football
2               S  ee441df8-f44d-3452-abf3-80619a6b7376    Football
3              XL  63c009fa-41e9-37f7-8207-2131d668fc30    Football
4             XXL  7c41b818-d111-3baf-a3d9-2f0a21a35ff5    Football

  record_source
0  thread_exact
1  thread_exact
2  thread_exact
3  thread_exact
4  thread_exact

[5 rows x 35 columns]

In [2]:
print(df.info())
print(df.describe())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1447795 entries, 0 to 1447794
Data columns (total 35 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   snapshot_date          1447795 non-null  object
 1   country_code           1447795 non-null  object
 2   product_name           1447795 non-null  object
 3   model_number           1447795 non-null  object
 4   currency               1447795 non-null  object
 5   price_local            1447795 non-null  float64
 6   sale_price_local       210687 non-null   float64
 7   gender_segment         1441048 non-null  object
 8   size_label             1447793 non-null  object
 9   category               1447795 non-null  object
 10  subcategory            1447767 non-null  object
 11  product_id             1447795 non-null  object
 12  sku                    1447793 non-null  object
 13  style_color            1447795 non-null  object
 14  brand_name             1447478 non-null  object
 15  color_name             1447748 non-null  object
 16  size_count             0 non-null        float64
 17  available_size_count   0 non-null        float64
 18  available              1447795 non-null  bool
 19  availability_level     1447793 non-null  object
 20  available_market       1447795 non-null  bool
 21  in_stock               1447795 non-null  bool
 22  discount_pct           1447777 non-null  float64
 23  employee_price         0 non-null        float64
 24  product_url            1447795 non-null  object
 25  canonical_url          1447795 non-null  object
 26  image_url              1447795 non-null  object
 27  gtin                   0 non-null        float64
 28  stock_keeping_unit_id  1447793 non-null  float64
 29  catalog_sku_id         1447793 non-null  object
 30  nike_size              1447793 non-null  object
 31  localized_size         1444423 non-null  object
 32  size_conversion_id     1410975 non-null  object
 33  sport_tags             1445530 non-null  object
 34  record_source          1447795 non-null  object
dtypes: bool(3), float64(8), object(24)
memory usage: 357.6+ MB
None
        price_local  sale_price_local  size_count  available_size_count  \
count  1.447795e+06      2.106870e+05         0.0                   0.0
mean   6.555476e+04      1.360314e+05         NaN                   NaN
std    4.386498e+05      6.354138e+05         NaN                   NaN
min    0.000000e+00      8.990000e+00         NaN                   NaN
25%    7.499000e+01      1.099900e+02         NaN                   NaN
50%    1.399900e+02      3.690000e+02         NaN                   NaN
75%    6.299900e+02      3.149000e+03         NaN                   NaN
max    1.079900e+07      1.030900e+07         NaN                   NaN

       discount_pct  employee_price  gtin  stock_keeping_unit_id
count  1.447777e+06             0.0   0.0           1.447793e+06
mean   3.600409e+00             NaN   NaN           9.032503e+08
std    9.167788e+00             NaN   NaN           2.984759e+08
min   -2.027270e+01             NaN   NaN           1.000702e+07
25%    0.000000e+00             NaN   NaN           1.004106e+09
50%    0.000000e+00             NaN   NaN           1.005086e+09
75%    0.000000e+00             NaN   NaN           1.005424e+09
max    5.081540e+01             NaN   NaN           1.007658e+09
snapshot_date                  0
country_code                   0
product_name                   0
model_number                   0
currency                       0
price_local                    0
sale_price_local         1237108
gender_segment              6747
size_label                     2
category                       0
subcategory                   28
product_id                     0
sku                            2
style_color                    0
brand_name                   317
color_name                    47
size_count               1447795
available_size_count     1447795
available                      0
availability_level             2
available_market               0
in_stock                       0
discount_pct                  18
employee_price           1447795
product_url                    0
canonical_url                  0
image_url                      0
gtin                     1447795
stock_keeping_unit_id          2
catalog_sku_id                 2
nike_size                      2
localized_size              3372
size_conversion_id         36820
sport_tags                  2265
record_source                  0
dtype: int64

In [3]:
# Convert snapshot_date to datetime
df['snapshot_date'] = pd.to_datetime(df['snapshot_date'])

# Drop completely empty columns
df = df.drop(columns=['size_count', 'available_size_count', 'record_source'])

# Optional: drop sparse columns if not needed
df = df.drop(columns=['sport_tags'])

# Fill missing gender_segment with 'Unknown'
df['gender_segment'] = df['gender_segment'].fillna('Unknown')

# Fill missing brand_name with 'Unknown'
df['brand_name'] = df['brand_name'].fillna('Unknown')

# Fill missing sale_price_local with price_local (assumes not on sale)
df['sale_price_local'] = df['sale_price_local'].fillna(df['price_local'])

In [4]:
print(df['country_code'].nunique())
print(df['category'].nunique())

45
5

In [5]:
print(df.duplicated(subset=['snapshot_date','product_id']).sum())

1418077

In [6]:
df['snapshot_date'] = pd.to_datetime(df['snapshot_date'])

In [7]:
print(df['country_code'].nunique())
print(df['category'].unique())
print(df['gender_segment'].unique())

45
['APPAREL' 'EQUIPMENT' 'FOOTWEAR' 'DIGITAL_GIFT_CARD' 'PHYSICAL_GIFT_CARD']
['MEN' 'WOMEN' 'MEN|WOMEN' 'BOYS|GIRLS' 'BOYS' 'Unknown'
 'MEN|BOYS|WOMEN|GIRLS' 'GIRLS' 'MEN|WOMEN|GIRLS' 'WOMEN|GIRLS'
 'MEN|BOYS|GIRLS' 'BOYS|WOMEN|GIRLS' 'GIRLS|BOYS' 'WOMEN|MEN']

In [8]:
df['discount'] = df['price_local'] - df['sale_price_local']

In [9]:
print(df[['price_local', 'sale_price_local', 'discount']].head())

   price_local  sale_price_local  discount
0        110.0             110.0       0.0
1        110.0             110.0       0.0
2        110.0             110.0       0.0
3        110.0             110.0       0.0
4        110.0             110.0       0.0

In [10]:
df['discount'] = df['price_local'] - df['sale_price_local']

In [11]:
df['sale_price_local'] = df['sale_price_local'].fillna(df['price_local'])

In [12]:
df['discount'] = df['price_local'] - df['sale_price_local']

In [13]:
print(df[['price_local', 'sale_price_local', 'discount']].head())

   price_local  sale_price_local  discount
0        110.0             110.0       0.0
1        110.0             110.0       0.0
2        110.0             110.0       0.0
3        110.0             110.0       0.0
4        110.0             110.0       0.0

In [14]:
df['is_on_sale'] = df['price_local'] != df['sale_price_local']

In [15]:
print(df['is_on_sale'].value_counts())

is_on_sale
False    1237108
True      210687
Name: count, dtype: int64

In [16]:
df.groupby('category')['is_on_sale'].mean()

category
APPAREL               0.130009
DIGITAL_GIFT_CARD     0.000000
EQUIPMENT             0.090379
FOOTWEAR              0.162444
PHYSICAL_GIFT_CARD    0.000000
Name: is_on_sale, dtype: float64

In [17]:
df['discount_pct'] = (df['price_local'] - df['sale_price_local']) / df['price_local'] * 100

In [18]:
df.groupby('category')['discount_pct'].describe()

,count,mean,std,min,25%,50%,75%,max
category,,,,,,,,
APPAREL,696577.0,-4.447152,12.330068,-103.315608,0.0,0.0,0.0,0.0
DIGITAL_GIFT_CARD,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EQUIPMENT,26389.0,-2.729593,9.611276,-100.000000,0.0,0.0,0.0,0.0
FOOTWEAR,724811.0,-5.560476,13.847482,-100.160256,0.0,0.0,0.0,0.0
PHYSICAL_GIFT_CARD,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
# Create Products table
products = df[['product_id','product_name','model_number','category','subcategory','brand_name','gender_segment']].drop_duplicates()

# Create Prices table
prices = df[['product_id','snapshot_date','currency','price_local','sale_price_local','discount','discount_pct','is_on_sale']]

# Create Inventory table
inventory = df[['product_id','available','size_label','sku','availability_level']]

In [26]:
products.to_csv("C:/Users/sreej/OneDrive/Desktop/Power BI PROJECT/NIKE SALES PROJECT/products.csv", index=False)

prices.to_csv("C:/Users/sreej/OneDrive/Desktop/Power BI PROJECT/NIKE SALES PROJECT/prices.csv", index=False)

inventory.to_csv("C:/Users/sreej/OneDrive/Desktop/Power BI PROJECT/NIKE SALES PROJECT/inventory.csv", index=False)

In [27]:
# Discount percentage (if not already)
df['discount_pct'] = (df['price_local'] - df['sale_price_local']) / df['price_local'] * 100

# Price bucket (very important for storytelling)
df['price_bucket'] = pd.cut(df['price_local'],
                           bins=[0,50,100,200,500,1000],
                           labels=['Low','Budget','Mid','Premium','Luxury'])

In [30]:
df[df['discount'] < 0][['price_local', 'sale_price_local', 'discount']].head()

    price_local  sale_price_local  discount
50        21.97              30.0     -8.03
51        21.97              30.0     -8.03
52        21.97              30.0     -8.03
53        21.97              30.0     -8.03
54        21.97              30.0     -8.03

In [31]:
(df['discount'] < 0).sum()

210687

In [32]:
# Check how many
print((df['discount'] < 0).sum())

# Remove them
df = df[df['discount'] >= 0]

210687

In [33]:
df['discount_pct'] = (df['price_local'] - df['sale_price_local']) / df['price_local'] * 100

In [34]:
df[df['discount'] < 0][['price_local','sale_price_local','country_code','category']].head(20)

Empty DataFrame
Columns: [price_local, sale_price_local, country_code, category]
Index: []

In [35]:
df['discount'].describe()

count    1237108.0
mean           0.0
std            0.0
min            0.0
25%            0.0
50%            0.0
75%            0.0
max            0.0
Name: discount, dtype: float64

In [36]:
df['sale_price_local'] = df[['price_local','sale_price_local']].min(axis=1)
df['discount'] = df['price_local'] - df['sale_price_local']

In [37]:
df['discount_pct'] = (df['price_local'] - df['sale_price_local']) / df['price_local'] * 100
(df['discount'] < 0).sum()

0

In [38]:
df['sale_price_local'] = df[['price_local','sale_price_local']].min(axis=1)

In [39]:
df[df['sale_price_local'].notna()][['price_local','sale_price_local','category']].head(20)

    price_local  sale_price_local category
0         110.0             110.0  APPAREL
1         110.0             110.0  APPAREL
2         110.0             110.0  APPAREL
3         110.0             110.0  APPAREL
4         110.0             110.0  APPAREL
5         130.0             130.0  APPAREL
6         130.0             130.0  APPAREL
7         130.0             130.0  APPAREL
8         130.0             130.0  APPAREL
9         130.0             130.0  APPAREL
10        130.0             130.0  APPAREL
11        190.0             190.0  APPAREL
12        190.0             190.0  APPAREL
13        190.0             190.0  APPAREL
14        190.0             190.0  APPAREL
15        190.0             190.0  APPAREL
16        190.0             190.0  APPAREL
17        160.0             160.0  APPAREL
18        160.0             160.0  APPAREL
19        160.0             160.0  APPAREL

In [40]:
# Convert to datetime, coerce errors to NaT (null)
df['snapshot_date'] = pd.to_datetime(df['snapshot_date'], errors='coerce')

# Remove rows where snapshot_date could not be parsed
df_clean = df.dropna(subset=['snapshot_date'])

# Export final CSV
df_clean.to_csv("C:/Users/sreej/OneDrive/Desktop/Power BI PROJECT/final_nike_data_clean.csv", index=False)

In [29]:
df.to_csv("C:/Users/sreej/OneDrive/Desktop/Power BI PROJECT/NIKE SALES PROJECT/final_nike_data.csv", index=False)